# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: second/protos/box_coder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='second/protos/box_coder.proto',
  package='second.protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dsecond/protos/box_coder.proto\x12\rsecond.protos\"\x8b\x01\n\x08\x42oxCoder\x12=\n\x12ground_box3d_coder\x18\x01 \x01(\x0b\x32\x1f.second.protos.GroundBox3dCoderH\x00\x12\x33\n\rbev_box_coder\x18\x02 \x01(\x0b\x32\x1a.second.protos.BevBoxCoderH\x00\x42\x0b\n\tbox_coder\"C\n\x10GroundBox3dCoder\x12\x12\n\nlinear_dim\x18\x01 \x01(\x08\x12\x1b\n\x13\x65ncode_angle_vector\x18\x02 \x01(\x08\"`\n\x0b\x42\x65vBoxCoder\x12\x12\n\nlinear_dim\x18\x01 \x01(\x08\x12\x1b\n\x13\x65ncode_angle_vector\x18\x02 \x01(\x08\x12\x0f\n\x07z_fixed\x18\x03 \x01(\x02\x12\x0f\n\x07h_fixed\x18\x04 \x01(\x02\x62\x06proto3')
)




_BOXCODER = _descriptor.Descriptor(
  name='BoxCoder',
  full_name='second.protos.BoxCoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ground_box3d_coder', full_name='second.protos.BoxCoder.ground_box3d_coder', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bev_box_coder', full_name='second.protos.BoxCoder.bev_box_coder', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='box_coder', full_name='second.protos.BoxCoder.box_coder',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=49,
  serialized_end=188,
)


_GROUNDBOX3DCODER = _descriptor.Descriptor(
  name='GroundBox3dCoder',
  full_name='second.protos.GroundBox3dCoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_dim', full_name='second.protos.GroundBox3dCoder.linear_dim', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encode_angle_vector', full_name='second.protos.GroundBox3dCoder.encode_angle_vector', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=257,
)


_BEVBOXCODER = _descriptor.Descriptor(
  name='BevBoxCoder',
  full_name='second.protos.BevBoxCoder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_dim', full_name='second.protos.BevBoxCoder.linear_dim', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encode_angle_vector', full_name='second.protos.BevBoxCoder.encode_angle_vector', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z_fixed', full_name='second.protos.BevBoxCoder.z_fixed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h_fixed', full_name='second.protos.BevBoxCoder.h_fixed', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=355,
)

_BOXCODER.fields_by_name['ground_box3d_coder'].message_type = _GROUNDBOX3DCODER
_BOXCODER.fields_by_name['bev_box_coder'].message_type = _BEVBOXCODER
_BOXCODER.oneofs_by_name['box_coder'].fields.append(
  _BOXCODER.fields_by_name['ground_box3d_coder'])
_BOXCODER.fields_by_name['ground_box3d_coder'].containing_oneof = _BOXCODER.oneofs_by_name['box_coder']
_BOXCODER.oneofs_by_name['box_coder'].fields.append(
  _BOXCODER.fields_by_name['bev_box_coder'])
_BOXCODER.fields_by_name['bev_box_coder'].containing_oneof = _BOXCODER.oneofs_by_name['box_coder']
DESCRIPTOR.message_types_by_name['BoxCoder'] = _BOXCODER
DESCRIPTOR.message_types_by_name['GroundBox3dCoder'] = _GROUNDBOX3DCODER
DESCRIPTOR.message_types_by_name['BevBoxCoder'] = _BEVBOXCODER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoxCoder = _reflection.GeneratedProtocolMessageType('BoxCoder', (_message.Message,), dict(
  DESCRIPTOR = _BOXCODER,
  __module__ = 'second.protos.box_coder_pb2'
  # @@protoc_insertion_point(class_scope:second.protos.BoxCoder)
  ))
_sym_db.RegisterMessage(BoxCoder)

GroundBox3dCoder = _reflection.GeneratedProtocolMessageType('GroundBox3dCoder', (_message.Message,), dict(
  DESCRIPTOR = _GROUNDBOX3DCODER,
  __module__ = 'second.protos.box_coder_pb2'
  # @@protoc_insertion_point(class_scope:second.protos.GroundBox3dCoder)
  ))
_sym_db.RegisterMessage(GroundBox3dCoder)

BevBoxCoder = _reflection.GeneratedProtocolMessageType('BevBoxCoder', (_message.Message,), dict(
  DESCRIPTOR = _BEVBOXCODER,
  __module__ = 'second.protos.box_coder_pb2'
  # @@protoc_insertion_point(class_scope:second.protos.BevBoxCoder)
  ))
_sym_db.RegisterMessage(BevBoxCoder)


# @@protoc_insertion_point(module_scope)
